import Link from "next/link";
import { adminDate, requirePlatformAdmin } from "@/lib/platform/admin";
export const dynamic = "force-dynamic";
export default async function TypingCentres({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const query = await searchParams; const search = typeof query.q === "string" ? query.q.trim() : ""; const state = typeof query.state === "string" ? query.state : ""; const plan = typeof query.plan === "string" ? query.plan : ""; const page = Math.max(1, Number(query.page) || 1); const { admin } = await requirePlatformAdmin("/admin/typing-centres");
  let request = admin.from("organizations").select("id,name,business_email,phone,account_state,created_at,organization_subscriptions(plan,status,current_period_ends_at),organization_memberships(user_id,is_primary_owner,profiles(full_name,email))", { count: "exact" }).order("created_at", { ascending: false }); if (search) request = request.or(`name.ilike.%${search}%,business_email.ilike.%${search}%`); if (state) request = request.eq("account_state", state); const { data, count, error } = await request.range((page - 1) * 25, page * 25 - 1); if (error) throw error;
  const rows = (data ?? []).filter((row: any) => !plan || row.organization_subscriptions?.[0]?.plan === plan);
  return <><div className="admin-page-heading"><div><p>Tenant management</p><h1>Typing centres</h1><span>{count ?? 0} organizations on the platform.</span></div><Link className="primary-button" href="/admin/typing-centres/new">+ Add Typing Centre</Link></div><form className="admin-filters"><input name="q" defaultValue={search} placeholder="Search name or email"/><select name="state" defaultValue={state}><option value="">All statuses</option>{["active","trial","paused","suspended","cancelled"].map(x => <option key={x}>{x}</option>)}</select><select name="plan" defaultValue={plan}><option value="">All plans</option>{["starter","business","pro"].map(x => <option key={x}>{x}</option>)}</select><button>Filter</button></form><section className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Typing centre</th><th>Contact</th><th>Plan</th><th>Subscription</th><th>Renewal</th><th>Account</th><th>Created</th></tr></thead><tbody>{rows.map((row: any) => { const sub = row.organization_subscriptions?.[0]; const owner = row.organization_memberships?.find((m: any) => m.is_primary_owner)?.profiles; return <tr key={row.id}><td><Link href={`/admin/typing-centres/${row.id}`}>{row.name}</Link></td><td>{owner?.full_name ?? "—"}<small>{row.phone || row.business_email || owner?.email}</small></td><td>{sub?.plan ?? "—"}</td><td>{sub?.status ?? "—"}</td><td>{adminDate(sub?.current_period_ends_at)}</td><td><span className="admin-badge">{row.account_state}</span></td><td>{adminDate(row.created_at)}</td></tr>; })}</tbody></table></section><div className="admin-pagination">{page > 1 && <Link href={`?q=${encodeURIComponent(search)}&page=${page-1}`}>Previous</Link>}<span>Page {page}</span>{(count ?? 0) > page * 25 && <Link href={`?q=${encodeURIComponent(search)}&page=${page+1}`}>Next</Link>}</div></>;
}
