import Link from "next/link";
import { adminDate, requirePlatformAdmin } from "@/lib/platform/admin";
export const dynamic = "force-dynamic";
export default async function TypingCentres({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const query = await searchParams; const search = typeof query.q === "string" ? query.q.trim().toLowerCase() : ""; const state = typeof query.state === "string" ? query.state : ""; const plan = typeof query.plan === "string" ? query.plan : ""; const page = Math.max(1, Number(query.page) || 1); const { admin } = await requirePlatformAdmin("/admin/typing-centres");
  const [organizations, subscriptions, memberships] = await Promise.all([admin.from("organizations").select("id,name,business_email,phone,account_state,created_at").order("created_at", { ascending: false }), admin.from("organization_subscriptions").select("organization_id,plan,status,current_period_ends_at"), admin.from("organization_memberships").select("organization_id,user_id,is_primary_owner").eq("status", "active")]);
  if (organizations.error) throw organizations.error; if (subscriptions.error) throw subscriptions.error; if (memberships.error) throw memberships.error;
  const primary = (memberships.data ?? []).filter((m: any) => m.is_primary_owner); const ids = [...new Set(primary.map((m: any) => m.user_id))]; const { data: profiles, error: profileError } = ids.length ? await admin.from("profiles").select("id,full_name,email").in("id", ids) : { data: [], error: null }; if (profileError) throw profileError;
  const profileById = new Map((profiles ?? []).map((p: any) => [p.id, p])); const subscriptionByOrg = new Map((subscriptions.data ?? []).map((s: any) => [s.organization_id, s])); const ownerByOrg = new Map(primary.map((m: any) => [m.organization_id, profileById.get(m.user_id)]));
  const filtered = (organizations.data ?? []).filter((o: any) => { const subscription: any = subscriptionByOrg.get(o.id); return (!search || `${o.name} ${o.business_email ?? ""}`.toLowerCase().includes(search)) && (!state || o.account_state === state) && (!plan || subscription?.plan === plan); }); const pageSize = 25; const rows = filtered.slice((page - 1) * pageSize, page * pageSize);
  return <><div className="admin-page-heading"><div><p>Tenant management</p><h1>Typing centres</h1><span>{filtered.length} organizations on the platform.</span></div><Link className="primary-button" href="/admin/typing-centres/new">+ Add Typing Centre</Link></div><form className="admin-filters"><input name="q" defaultValue={search} placeholder="Search name or email"/><select name="state" defaultValue={state}><option value="">All statuses</option>{["active","trial","paused","suspended","cancelled"].map(x => <option key={x}>{x}</option>)}</select><select name="plan" defaultValue={plan}><option value="">All plans</option>{["starter","business","pro"].map(x => <option key={x}>{x}</option>)}</select><button>Filter</button></form><section className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Typing centre</th><th>Contact</th><th>Plan</th><th>Subscription</th><th>Renewal</th><th>Account</th><th>Created</th></tr></thead><tbody>{rows.map((o: any) => { const sub: any = subscriptionByOrg.get(o.id); const owner: any = ownerByOrg.get(o.id); return <tr key={o.id}><td><Link href={`/admin/typing-centres/${o.id}`}>{o.name}</Link></td><td>{owner?.full_name ?? "—"}<small>{o.phone || o.business_email || owner?.email}</small></td><td>{sub?.plan ?? "—"}</td><td>{sub?.status ?? "—"}</td><td>{adminDate(sub?.current_period_ends_at)}</td><td><span className="admin-badge">{o.account_state}</span></td><td>{adminDate(o.created_at)}</td></tr>; })}</tbody></table></section><div className="admin-pagination">{page > 1 && <Link href={`?q=${encodeURIComponent(search)}&state=${state}&plan=${plan}&page=${page - 1}`}>Previous</Link>}<span>Page {page}</span>{filtered.length > page * pageSize && <Link href={`?q=${encodeURIComponent(search)}&state=${state}&plan=${plan}&page=${page + 1}`}>Next</Link>}</div></>;
}
