"use server";
import { redirect } from "next/navigation";
import { headers } from "next/headers";
import { getSupabaseServerClient } from "@/lib/supabase/server";
import { loginSchema, onboardingSchema, resetPasswordSchema, resetRequestSchema, safeNext, signupSchema } from "@/lib/auth/validation";
import { resolveAuthDestination } from "@/lib/auth/destination";
export type SignupState = { error?: string; status?: "verification"; email?: string };
async function requestOrigin() { const requestHeaders = await headers(); const host = requestHeaders.get("x-forwarded-host") ?? requestHeaders.get("host"); const protocol = requestHeaders.get("x-forwarded-proto") ?? "https"; if (host && (host.endsWith(".vercel.app") || host === "noteitapp.com" || host === "www.noteitapp.com" || host.startsWith("localhost:"))) return `${protocol}://${host}`; return (process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000").replace(/\/$/, ""); }
async function signOutDemoSession() { const supabase = await getSupabaseServerClient(); if (!supabase) return; const { data: { user } } = await supabase.auth.getUser(); if (!user) return; const { data: membership } = await supabase.from("organization_memberships").select("organization_id").eq("user_id", user.id).eq("status", "active").limit(1).maybeSingle(); if (!membership) return; const { data: organization } = await supabase.from("organizations").select("slug").eq("id", membership.organization_id).maybeSingle(); if (organization?.slug === "note-it-demo") await supabase.auth.signOut(); }
export async function signupAction(_: SignupState, formData: FormData): Promise<SignupState> { const parsed = signupSchema.safeParse(Object.fromEntries(formData)); if (!parsed.success) return { error: parsed.error.issues.some((issue) => issue.path.includes("confirmPassword")) ? "Passwords do not match." : "Use a valid email, your name, and a password of at least 12 characters." }; const supabase = await getSupabaseServerClient(); if (!supabase) return { error: "Production authentication is not configured." }; const { data: { user: existingUser } } = await supabase.auth.getUser(); if (existingUser) { await signOutDemoSession(); const { data: { user: remainingUser } } = await supabase.auth.getUser(); if (remainingUser) redirect((await resolveAuthDestination()) as never); } const origin = await requestOrigin(); const { data, error } = await supabase.auth.signUp({ email: parsed.data.email, password: parsed.data.password, options: { emailRedirectTo: `${origin}/auth/callback?next=/onboarding`, data: { full_name: parsed.data.displayName } } }); if (error) return { error: error.message.toLowerCase().includes("registered") ? "An account already exists for this email. Sign in instead." : "We could not create the account. Check your details and try again." }; if (data.session) redirect("/onboarding" as never); return { status: "verification", email: parsed.data.email }; }
export async function resendSignupAction(_: SignupState, formData: FormData): Promise<SignupState> { const email = String(formData.get("email") ?? "").trim().toLowerCase(); if (!loginSchema.shape.email.safeParse(email).success) return { error: "Enter a valid email address." }; const supabase = await getSupabaseServerClient(); if (!supabase) return { error: "Production authentication is not configured." }; const origin = await requestOrigin(); await supabase.auth.resend({ type: "signup", email, options: { emailRedirectTo: `${origin}/auth/callback?next=/onboarding` } }); return { status: "verification", email }; }
export async function loginAction(_: { error?: string }, formData: FormData) { const parsed = loginSchema.safeParse(Object.fromEntries(formData)); if (!parsed.success) return { error: "Enter a valid email and password." }; const supabase = await getSupabaseServerClient(); if (!supabase) return { error: "Production authentication is not configured." }; const { error } = await supabase.auth.signInWithPassword({ email: parsed.data.email, password: parsed.data.password }); if (error) return { error: "We could not sign you in. Check your details and try again." }; redirect((safeNext(parsed.data.next) ?? await resolveAuthDestination()) as never); }
export async function resetRequestAction(_: { message?: string }, formData: FormData) { const parsed = resetRequestSchema.safeParse(Object.fromEntries(formData)); if (!parsed.success) return { message: "If that address is registered, a reset link will be sent." }; const supabase = await getSupabaseServerClient(); const appUrl = (process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000").replace(/\/$/, ""); if (supabase) await supabase.auth.resetPasswordForEmail(parsed.data.email, { redirectTo: `${appUrl}/auth/callback?next=/reset-password` }); return { message: "If that address is registered, a reset link will be sent." }; }
export async function resetPasswordAction(_: { error?: string }, formData: FormData) { const parsed = resetPasswordSchema.safeParse(Object.fromEntries(formData)); if (!parsed.success) return { error: "Use matching passwords of at least 12 characters." }; const supabase = await getSupabaseServerClient(); if (!supabase) return { error: "Production authentication is not configured." }; const { error } = await supabase.auth.updateUser({ password: parsed.data.password }); if (error) return { error: "Your recovery session has expired. Request another link." }; redirect("/login?reset=success" as never); }
export async function onboardAction(_: { error?: string }, formData: FormData) { const parsed = onboardingSchema.safeParse({ ...Object.fromEntries(formData), acceptTerms: formData.get("acceptTerms") === "true" }); if (!parsed.success) return { error: "Enter the workspace details and accept the terms." }; const supabase = await getSupabaseServerClient(); if (!supabase) return { error: "Production authentication is not configured." }; const { data, error } = await (supabase as any).rpc("provision_current_user_workspace", { workspace_name: parsed.data.name, workspace_location: parsed.data.location, owner_display_name: parsed.data.displayName, workspace_phone: parsed.data.phone || null }); if (error || !data) return { error: "We could not create the workspace. Please try again." }; redirect("/onboarding/setup" as never); }
export async function logoutAction() { const supabase = await getSupabaseServerClient(); await supabase?.auth.signOut(); redirect("/login" as never); }
