"use server";
import { redirect } from "next/navigation";
import { getSupabaseServerClient } from "@/lib/supabase/server";
import { loginSchema, onboardingSchema, resetPasswordSchema, resetRequestSchema, safeNext } from "@/lib/auth/validation";
import { resolveAuthDestination } from "@/lib/auth/destination";
export async function loginAction(_: { error?: string }, formData: FormData) { const parsed = loginSchema.safeParse(Object.fromEntries(formData)); if (!parsed.success) return { error: "Enter a valid email and password." }; const supabase = await getSupabaseServerClient(); if (!supabase) return { error: "Production authentication is not configured." }; const { error } = await supabase.auth.signInWithPassword({ email: parsed.data.email, password: parsed.data.password }); if (error) return { error: "We could not sign you in. Check your details and try again." }; redirect((safeNext(parsed.data.next) ?? await resolveAuthDestination()) as never); }
export async function resetRequestAction(_: { message?: string }, formData: FormData) { const parsed = resetRequestSchema.safeParse(Object.fromEntries(formData)); if (!parsed.success) return { message: "If that address is registered, a reset link will be sent." }; const supabase = await getSupabaseServerClient(); if (supabase) await supabase.auth.resetPasswordForEmail(parsed.data.email, { redirectTo: `${process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000"}/reset-password` }); return { message: "If that address is registered, a reset link will be sent." }; }
export async function resetPasswordAction(_: { error?: string }, formData: FormData) { const parsed = resetPasswordSchema.safeParse(Object.fromEntries(formData)); if (!parsed.success) return { error: "Use matching passwords of at least 12 characters." }; const supabase = await getSupabaseServerClient(); if (!supabase) return { error: "Production authentication is not configured." }; const { error } = await supabase.auth.updateUser({ password: parsed.data.password }); if (error) return { error: "Your recovery session has expired. Request another link." }; redirect("/login?reset=success" as never); }
export async function onboardAction(_: { error?: string }, formData: FormData) { const parsed = onboardingSchema.safeParse(Object.fromEntries(formData)); if (!parsed.success) return { error: "Check the organization details and accept the terms." }; const supabase = await getSupabaseServerClient(); if (!supabase) return { error: "Production authentication is not configured." }; const { data, error } = await supabase.rpc("onboard_current_user", { organization_name: parsed.data.name, organization_slug: parsed.data.slug, organization_location: parsed.data.location, organization_email: parsed.data.email, organization_phone: parsed.data.phone, organization_whatsapp: parsed.data.whatsapp ?? "", organization_address: parsed.data.address ?? "", organization_color: parsed.data.primaryColor, subscription_plan: "starter" }); if (error || !data) return { error: "We could not create the organization. Try another slug." }; redirect("/dashboard" as never); }
export async function logoutAction() { const supabase = await getSupabaseServerClient(); await supabase?.auth.signOut(); redirect("/login" as never); }
