import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { WorkspaceShell } from "@/components/workspace-shell";
import { getWorkspaceContext } from "@/lib/workspace/context";

export const dynamic = "force-dynamic";
const label = (value: string) => value.replaceAll("_", " ");

export default async function ImportDetailPage({ params, searchParams }: { params: Promise<{ jobId: string }>; searchParams: Promise<{ page?: string; status?: string }> }) {
  const context = await getWorkspaceContext("/settings"); if (!context) redirect("/login" as never);
  const { jobId } = await params; const query = await searchParams; const page = Math.max(1, Number(query.page ?? 1)); const size = 50;
  const { data: job } = await context.supabase.from("import_jobs").select("*,profiles(full_name,email)").eq("id", jobId).eq("organization_id", context.organization.id).maybeSingle(); if (!job) notFound();
  let rowsQuery = context.supabase.from("import_job_rows").select("id,row_number,status,issues,resolution,customer_id,company_id,document_id", { count: "exact" }).eq("import_job_id", jobId).eq("organization_id", context.organization.id).order("row_number").range((page - 1) * size, page * size - 1);
  if (query.status) rowsQuery = rowsQuery.eq("status", query.status as never); const { data: rows, count } = await rowsQuery;
  return <WorkspaceShell organizationName={context.organization.name} activePath="/settings"><header className="page-heading"><p className="eyebrow">Data import</p><h1>Import Details</h1><p>{job.file_name} · {job.source_format.toUpperCase()}</p></header><section className="panel"><dl><dt>Status</dt><dd>{label(job.status)}</dd><dt>Imported by</dt><dd>{(job.profiles as any)?.full_name ?? (job.profiles as any)?.email ?? "Workspace owner"}</dd><dt>Rows detected</dt><dd>{job.total_rows}</dd><dt>Created</dt><dd>{job.customers_created + job.companies_created + job.documents_created}</dd><dt>Updated</dt><dd>{job.records_updated}</dd><dt>Skipped</dt><dd>{job.records_skipped}</dd><dt>Failed</dt><dd>{job.records_failed}</dd></dl><a className="primary-button" href={`/api/imports/${job.id}/error-report`}>Download Error Report</a></section><section className="panel"><h2>Mapping used</h2><div className="table-wrap"><table><thead><tr><th>Source column</th><th>Destination</th></tr></thead><tbody>{Object.entries(job.mapping ?? {}).map(([source, destination]) => <tr key={source}><td>{source}</td><td>{label(String(destination))}</td></tr>)}</tbody></table></div></section><section className="panel"><h2>Row results</h2><p>{count ?? 0} rows</p><div className="import-filter-links">{["", "imported", "skipped", "failed", "invalid", "possible_duplicate"].map((status) => <Link key={status} href={`/settings/data-import/${jobId}?${status ? `status=${status}` : ""}`}>{status ? label(status) : "All"}</Link>)}</div><div className="table-wrap"><table><thead><tr><th>Row</th><th>Status</th><th>Resolution</th><th>Details</th></tr></thead><tbody>{(rows ?? []).map((row: any) => <tr key={row.id}><td>{row.row_number}</td><td>{label(row.status)}</td><td>{row.resolution ?? "—"}</td><td>{Array.isArray(row.issues) ? row.issues.join(" ") : "—"}</td></tr>)}</tbody></table></div>{page > 1 && <Link href={`/settings/data-import/${jobId}?page=${page - 1}`}>Previous</Link>} {(count ?? 0) > page * size && <Link href={`/settings/data-import/${jobId}?page=${page + 1}`}>Next</Link>}</section></WorkspaceShell>;
}
