import Link from "next/link";
import { redirect } from "next/navigation";
import { ArchiveDialog } from "@/components/archive-dialog";
import { archiveCompanyAction } from "@/features/crm/actions";
import { WorkspaceShell } from "@/components/workspace-shell";
import { getWorkspaceContext } from "@/lib/workspace/context";
import { listParams } from "@/lib/workspace/utils";
export const dynamic="force-dynamic";
export default async function Companies({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){const context=await getWorkspaceContext();if(!context)redirect("/account-inactive" as never);const params=listParams(await searchParams,["updated_at","name","city"]);let query=context.supabase.from("companies").select("id,name,trade_name,licence_number,city,updated_at",{count:"exact"}).eq("organization_id",context.organization.id).is("archived_at",null).order(params.sort,{ascending:params.direction==="asc"});if(params.search.length>=2)query=query.ilike("name",`%${params.search}%`);const {data,count}=await query.range((params.page-1)*params.pageSize,params.page*params.pageSize-1);return <WorkspaceShell organizationName={context.organization.name}><header className="page-heading split"><div><p className="eyebrow">Companies</p><h1>Companies</h1></div><Link className="primary-button" href="/companies/new">Add company</Link></header><form className="filter-bar"><label>Search companies<input name="search" defaultValue={params.search} placeholder="Search company name"/></label><select name="sort" defaultValue={params.sort}><option value="updated_at">Recently updated</option><option value="name">Name</option><option value="city">Emirate</option></select><button>Apply</button></form><section className="panel table-panel">{data?.length?<table><thead><tr><th>Company</th><th>Licence</th><th>Emirate</th><th>Actions</th></tr></thead><tbody>{data.map((company:any)=><tr key={company.id}><td><Link href={`/companies/${company.id}`}><b>{company.name}</b></Link><small>{company.trade_name||"No trade name recorded"}</small></td><td>{company.licence_number||"-"}</td><td>{company.city}</td><td><div className="actions"><Link href={`/companies/${company.id}`}>View</Link><Link href={`/companies/${company.id}/edit`}>Edit</Link><ArchiveDialog action={archiveCompanyAction} fields={{companyId:company.id}} entityName={company.name} title="Archive company?" description="This removes the company from active lists. Existing branches, customers and historical records remain retained." confirmLabel="Archive Company"/></div></td></tr>)}</tbody></table>:<div className="empty-state">No companies match this workspace.</div>}</section><p className="pagination">{count??0} company records</p></WorkspaceShell>}
