import { appConfig } from "@/lib/config/app";

export type ExpiryStatus = "valid" | "expiring_soon" | "urgent" | "expires_today" | "expired" | "renewal_in_progress" | "unknown";
function asDate(value: string | Date | undefined) { if (!value) return undefined; const date = new Date(value); return Number.isNaN(date.getTime()) ? undefined : date; }
export function calculateDaysRemaining(expiryDate: string | Date | undefined, now = new Date()) { const expiry = asDate(expiryDate); if (!expiry) return undefined; return Math.floor((Date.UTC(expiry.getUTCFullYear(), expiry.getUTCMonth(), expiry.getUTCDate()) - Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate())) / 86_400_000); }
export function determineExpiryStatus(expiryDate: string | Date | undefined, renewalInProgress = false, now = new Date()): ExpiryStatus { if (renewalInProgress) return "renewal_in_progress"; const days = calculateDaysRemaining(expiryDate, now); if (days === undefined) return "unknown"; if (days < 0) return "expired"; if (days === 0) return "expires_today"; if (days <= 7) return "urgent"; if (days <= 30) return "expiring_soon"; return "valid"; }
export function getRelativeExpiryText(expiryDate: string | Date | undefined, now = new Date()) { const days = calculateDaysRemaining(expiryDate, now); if (days === undefined) return "Expiry date unavailable"; if (days < -1) return `Expired ${Math.abs(days)} days ago`; if (days === -1) return "Expired yesterday"; if (days === 0) return "Today"; if (days === 1) return "Tomorrow"; return `In ${days} days`; }
export function formatDisplayDate(value: string | Date | undefined) { const date = asDate(value); return date ? new Intl.DateTimeFormat(appConfig.locale, { timeZone: appConfig.timezone, day: "numeric", month: "short", year: "numeric" }).format(date) : "—"; }
export function formatDateTime(value: string | Date | undefined) { const date = asDate(value); return date ? new Intl.DateTimeFormat(appConfig.locale, { timeZone: appConfig.timezone, dateStyle: "medium", timeStyle: "short" }).format(date) : "—"; }
