"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { getWorkspaceContext } from "@/lib/workspace/context";
import { safeDatabaseError } from "@/lib/workspace/utils";
import { branchSchema, companySchema, customerSchema, followUpSchema } from "./schemas";

const emptyToNull = (value: string | undefined) => value?.trim() || null;
function formValues(formData: FormData) { return Object.fromEntries(formData.entries()); }
async function workspaceOrRedirect() { const context = await getWorkspaceContext(); if (!context) redirect("/account-inactive" as never); return context; }
async function log(context: Awaited<ReturnType<typeof workspaceOrRedirect>>, event: string, entityType: string, entityId: string) { await context.supabase.rpc("log_workspace_activity", { event_kind: event, entity_type: entityType, entity_id: entityId }); }

export async function createCompanyAction(formData: FormData) { const parsed = companySchema.safeParse(formValues(formData)); if (!parsed.success) redirect("/companies/new?error=validation" as never); const context = await workspaceOrRedirect(); const value = parsed.data; const { data, error } = await context.supabase.from("companies").insert({ organization_id: context.organization.id, name: value.name, city: value.city, licence_number: emptyToNull(value.licenceNumber), trade_name: emptyToNull(value.tradeName), industry: emptyToNull(value.industry), business_activity: emptyToNull(value.businessActivity), company_type: emptyToNull(value.companyType), contact_name: emptyToNull(value.contactName), contact_phone: emptyToNull(value.contactPhone), whatsapp_number: emptyToNull(value.whatsappNumber), contact_email: emptyToNull(value.contactEmail), address: emptyToNull(value.address), establishment_card_number: emptyToNull(value.establishmentCardNumber), immigration_file_number: emptyToNull(value.immigrationFileNumber), vat_registration_number: emptyToNull(value.vatRegistrationNumber), corporate_tax_registration_number: emptyToNull(value.corporateTaxRegistrationNumber) }).select("id").single(); if (error || !data) redirect(`/companies/new?error=${encodeURIComponent(safeDatabaseError(error))}` as never); await log(context, "company_created", "company", data.id); revalidatePath("/dashboard"); revalidatePath("/companies"); redirect(`/companies/${data.id}?created=1` as never); }

export async function updateCompanyAction(formData: FormData) { const companyId = String(formData.get("companyId") ?? ""); const parsed = companySchema.safeParse(formValues(formData)); if (!companyId || !parsed.success) redirect(`/companies/${companyId}?error=validation` as never); const context = await workspaceOrRedirect(); const value = parsed.data; const { data, error } = await context.supabase.from("companies").update({ name: value.name, city: value.city, licence_number: emptyToNull(value.licenceNumber), trade_name: emptyToNull(value.tradeName), industry: emptyToNull(value.industry), business_activity: emptyToNull(value.businessActivity), company_type: emptyToNull(value.companyType), contact_name: emptyToNull(value.contactName), contact_phone: emptyToNull(value.contactPhone), whatsapp_number: emptyToNull(value.whatsappNumber), contact_email: emptyToNull(value.contactEmail), address: emptyToNull(value.address), establishment_card_number: emptyToNull(value.establishmentCardNumber), immigration_file_number: emptyToNull(value.immigrationFileNumber), vat_registration_number: emptyToNull(value.vatRegistrationNumber), corporate_tax_registration_number: emptyToNull(value.corporateTaxRegistrationNumber) }).eq("id", companyId).select("id").maybeSingle(); if (error || !data) redirect(`/companies/${companyId}?error=${encodeURIComponent(safeDatabaseError(error))}` as never); await log(context, "company_updated", "company", data.id); revalidatePath("/companies"); revalidatePath(`/companies/${companyId}`); redirect(`/companies/${companyId}?updated=1` as never); }

export async function createBranchAction(formData: FormData) { const parsed = branchSchema.safeParse(formValues(formData)); const companyId = String(formData.get("companyId") ?? ""); if (!parsed.success || !companyId) redirect(`/companies/${companyId}?error=validation` as never); const context = await workspaceOrRedirect(); const { data: company } = await context.supabase.from("companies").select("id").eq("id", companyId).maybeSingle(); if (!company) redirect("/companies" as never); const value = parsed.data; const { data, error } = await context.supabase.from("branches").insert({ organization_id: context.organization.id, company_id: companyId, name: value.name, city: value.city, code: emptyToNull(value.code), contact_name: emptyToNull(value.contactName), phone: emptyToNull(value.phone), whatsapp_number: emptyToNull(value.whatsappNumber), email: emptyToNull(value.email), address: emptyToNull(value.address), trade_licence_number: emptyToNull(value.tradeLicenceNumber), notes: emptyToNull(value.notes) }).select("id").single(); if (error || !data) redirect(`/companies/${companyId}?error=${encodeURIComponent(safeDatabaseError(error))}` as never); await log(context, "branch_created", "branch", data.id); revalidatePath(`/companies/${companyId}`); redirect(`/companies/${companyId}?branch=created` as never); }

export async function archiveBranchAction(formData: FormData) { const branchId = String(formData.get("branchId") ?? ""); const companyId = String(formData.get("companyId") ?? ""); const context = await workspaceOrRedirect(); const { error } = await context.supabase.from("branches").update({ archived_at: new Date().toISOString(), is_active: false, status: "removed" }).eq("id", branchId); if (error) redirect(`/companies/${companyId}?error=${encodeURIComponent(safeDatabaseError(error))}` as never); await log(context, "branch_archived", "branch", branchId); revalidatePath(`/companies/${companyId}`); redirect(`/companies/${companyId}?branch=archived` as never); }

export async function updateBranchAction(formData: FormData) { const branchId = String(formData.get("branchId") ?? ""); const companyId = String(formData.get("companyId") ?? ""); const parsed = branchSchema.safeParse(formValues(formData)); if (!branchId || !companyId || !parsed.success) redirect(`/companies/${companyId}?error=validation` as never); const context = await workspaceOrRedirect(); const value = parsed.data; const { data, error } = await context.supabase.from("branches").update({ name: value.name, city: value.city, code: emptyToNull(value.code), contact_name: emptyToNull(value.contactName), phone: emptyToNull(value.phone), whatsapp_number: emptyToNull(value.whatsappNumber), email: emptyToNull(value.email), address: emptyToNull(value.address), trade_licence_number: emptyToNull(value.tradeLicenceNumber), notes: emptyToNull(value.notes) }).eq("id", branchId).eq("company_id", companyId).select("id").maybeSingle(); if (error || !data) redirect(`/companies/${companyId}?error=${encodeURIComponent(safeDatabaseError(error))}` as never); await log(context, "branch_updated", "branch", data.id); revalidatePath(`/companies/${companyId}`); redirect(`/companies/${companyId}?branch=updated` as never); }

export async function createCustomerAction(formData: FormData) { const parsed = customerSchema.safeParse(formValues(formData)); if (!parsed.success) redirect("/customers/new?error=validation" as never); const context = await workspaceOrRedirect(); const value = parsed.data; const { data, error } = await context.supabase.from("customers").insert({ organization_id: context.organization.id, full_name: value.fullName, customer_type: value.customerType, phone: value.phone, nationality: emptyToNull(value.nationality), email: emptyToNull(value.email), whatsapp_number: emptyToNull(value.whatsappNumber), passport_number: emptyToNull(value.passportNumber), emirates_id_number: emptyToNull(value.emiratesIdNumber), company_id: emptyToNull(value.companyId), branch_id: emptyToNull(value.branchId), date_of_birth: emptyToNull(value.dateOfBirth), gender: emptyToNull(value.gender), residential_address: emptyToNull(value.residentialAddress), sponsor_name: emptyToNull(value.sponsorName), sponsor_company: emptyToNull(value.sponsorCompany), visa_type: emptyToNull(value.visaType), profession: emptyToNull(value.profession), notes: emptyToNull(value.notes) }).select("id").single(); if (error || !data) redirect(`/customers/new?error=${encodeURIComponent(safeDatabaseError(error))}` as never); await log(context, "customer_created", "customer", data.id); revalidatePath("/dashboard"); revalidatePath("/customers"); redirect(`/customers/${data.id}?created=1` as never); }

export async function updateCustomerAction(formData: FormData) { const customerId = String(formData.get("customerId") ?? ""); const parsed = customerSchema.safeParse(formValues(formData)); if (!customerId || !parsed.success) redirect(`/customers/${customerId}?error=validation` as never); const context = await workspaceOrRedirect(); const value = parsed.data; const { data, error } = await context.supabase.from("customers").update({ full_name: value.fullName, customer_type: value.customerType, phone: value.phone, nationality: emptyToNull(value.nationality), email: emptyToNull(value.email), whatsapp_number: emptyToNull(value.whatsappNumber), passport_number: emptyToNull(value.passportNumber), emirates_id_number: emptyToNull(value.emiratesIdNumber), company_id: emptyToNull(value.companyId), branch_id: emptyToNull(value.branchId), date_of_birth: emptyToNull(value.dateOfBirth), gender: emptyToNull(value.gender), residential_address: emptyToNull(value.residentialAddress), sponsor_name: emptyToNull(value.sponsorName), sponsor_company: emptyToNull(value.sponsorCompany), visa_type: emptyToNull(value.visaType), profession: emptyToNull(value.profession), notes: emptyToNull(value.notes) }).eq("id", customerId).select("id").maybeSingle(); if (error || !data) redirect(`/customers/${customerId}?error=${encodeURIComponent(safeDatabaseError(error))}` as never); await log(context, "customer_updated", "customer", data.id); revalidatePath("/customers"); revalidatePath(`/customers/${customerId}`); redirect(`/customers/${customerId}?updated=1` as never); }

export async function createFollowUpAction(formData: FormData) { const parsed = followUpSchema.safeParse(formValues(formData)); const returnTo = String(formData.get("returnTo") ?? "/dashboard"); if (!parsed.success) redirect(`${returnTo}?error=validation` as never); const context = await workspaceOrRedirect(); const { data: customer } = await context.supabase.from("customers").select("id").eq("id", parsed.data.customerId).maybeSingle(); if (!customer) redirect("/customers" as never); const { data, error } = await context.supabase.from("follow_ups").insert({ organization_id: context.organization.id, customer_id: customer.id, due_at: parsed.data.dueAt, note: emptyToNull(parsed.data.note) }).select("id").single(); if (error || !data) redirect(`${returnTo}?error=${encodeURIComponent(safeDatabaseError(error))}` as never); await log(context, "follow_up_created", "follow_up", data.id); revalidatePath("/dashboard"); revalidatePath(returnTo); redirect(`${returnTo}?followUp=created` as never); }

export async function archiveCompanyAction(formData: FormData) { const companyId = String(formData.get("companyId") ?? ""); const context = await workspaceOrRedirect(); const { error } = await context.supabase.from("companies").update({ archived_at: new Date().toISOString(), is_active: false, status: "removed" }).eq("id", companyId); if (error) redirect(`/companies/${companyId}?error=${encodeURIComponent(safeDatabaseError(error))}` as never); await log(context, "company_archived", "company", companyId); revalidatePath("/companies"); redirect("/companies?archived=1" as never); }

export async function archiveCustomerAction(formData: FormData) { const customerId = String(formData.get("customerId") ?? ""); const context = await workspaceOrRedirect(); const { error } = await context.supabase.from("customers").update({ archived_at: new Date().toISOString(), is_active: false, status: "removed" }).eq("id", customerId); if (error) redirect(`/customers/${customerId}?error=${encodeURIComponent(safeDatabaseError(error))}` as never); await log(context, "customer_archived", "customer", customerId); revalidatePath("/customers"); redirect("/customers?archived=1" as never); }

export async function completeFollowUpAction(formData: FormData) { const followUpId = String(formData.get("followUpId") ?? ""); const customerId = String(formData.get("customerId") ?? ""); const context = await workspaceOrRedirect(); const { data, error } = await context.supabase.from("follow_ups").update({ status: "completed", completed_at: new Date().toISOString() }).eq("id", followUpId).select("id").maybeSingle(); if (error || !data) redirect(`/customers/${customerId}?error=${encodeURIComponent(safeDatabaseError(error))}` as never); await log(context, "follow_up_completed", "follow_up", data.id); revalidatePath("/dashboard"); revalidatePath(`/customers/${customerId}`); redirect(`/customers/${customerId}?followUp=completed` as never); }
