import type { Metadata } from "next";
import Link from "next/link";
import { NoteItLogo } from "@/components/note-it-logo";

export const metadata: Metadata = { title: "Note It | Document expiry and follow-up tracking for typing centers", description: "Track customer documents, expiry dates, renewals, follow-ups, and AI-assisted data entry in one workspace built for typing centers.", alternates: { canonical: "https://www.noteitapp.com/" } };
const features = [["Customers", "Keep customer details and document history together."], ["Documents", "See every document, status, and expiry date at a glance."], ["AI-assisted Extraction", "Upload an image or PDF, then review extracted details before saving."], ["Expiry & Renewals", "Prioritize expired, urgent, and upcoming renewals."], ["Follow-ups", "Schedule, complete, and track the next customer action."], ["Calendar", "View document expiries and follow-ups on one timeline."], ["Reports", "Understand expiry workload and renewal opportunities."], ["WhatsApp-ready reminders", "Configure workspace-level expiry summaries when messaging is enabled."]];
const steps = ["Add Customer", "Upload Document", "Review Extracted Details", "Track Expiry", "Follow Up"];

export default function HomePage() {
  return <div className="landing-page"><header className="landing-header"><Link href="/" aria-label="Note It home"><NoteItLogo className="landing-logo" /></Link><nav aria-label="Main navigation"><Link href="#features">Features</Link><Link href="/login">Login</Link><Link className="landing-button secondary" href="/demo">Open Demo</Link><Link className="landing-button primary desktop-cta" href="/signup">Create Your Workspace</Link></nav></header><main>
    <section className="landing-hero"><div><p className="landing-eyebrow">Built for busy typing centers</p><h1>Every customer document, expiry, and follow-up—under control.</h1><p className="landing-lead">Replace scattered files and chat reminders with a clear workspace for customer documents, renewals, and AI-assisted data entry.</p><div className="landing-actions"><Link className="landing-button primary" href="/demo">Open Demo</Link><Link className="landing-button secondary" href="/signup">Create Your Workspace</Link></div><small>Explore a shared workspace with sample data. It resets every 6 hours.</small></div><div className="hero-workflow" aria-label="Note It workflow preview"><span>Customer</span><b>Ahmed Hassan</b><span>Emirates ID</span><strong>Expires in 7 days</strong><span>Next action</span><b>Follow up tomorrow</b></div></section>
    <section className="landing-problem"><div><p className="landing-eyebrow">The daily reality</p><h2>Less time searching. Fewer renewals slipping through.</h2></div><ul><li>Documents spread across files and chats</li><li>Expiry dates noticed too late</li><li>Follow-ups managed from memory</li><li>Renewal opportunities lost</li></ul></section>
    <section className="landing-section" id="features"><header><p className="landing-eyebrow">One operational workspace</p><h2>Everything needed to move customer work forward</h2></header><div className="feature-grid">{features.map(([title, description], index) => <article key={title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{description}</p></article>)}</div></section>
    <section className="landing-section how-it-works"><header><p className="landing-eyebrow">How it works</p><h2>From document received to customer followed up</h2></header><ol>{steps.map((step, index) => <li key={step}><span>{index + 1}</span><b>{step}</b></li>)}</ol></section>
    <section className="landing-final-cta"><p className="landing-eyebrow">Ready when you are</p><h2>See Note It in action</h2><p>Explore the real workflow with safe sample data—no account setup required.</p><div className="landing-actions"><Link className="landing-button primary" href="/demo">Open Demo</Link><Link className="landing-button secondary" href="/signup">Create Your Workspace</Link></div></section>
  </main><footer className="landing-footer"><Link href="/" aria-label="Note It home"><NoteItLogo className="landing-logo" /></Link><nav aria-label="Footer"><Link href="/login">Login</Link><Link href="/privacy-policy">Privacy</Link><Link href="/terms">Terms</Link><a href="mailto:fazil@zorxmedia.com">Contact</a></nav><small>© {new Date().getFullYear()} Note It · Fusion Ventures FZ-LLC</small></footer></div>;
}
