import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { WorkspaceShell } from "@/components/workspace-shell";
import { createServiceFollowUpAction, recordServicePaymentAction, updateRequirementAction, updateServiceRequestDetailsAction, updateServiceRequestStatusAction } from "@/features/service-requests/actions";
import { getWorkspaceContext } from "@/lib/workspace/context";
import { allowedTransitions, money, requestStatuses, statusLabels, type RequestStatus } from "@/lib/service-requests/workflow";
import "../service-requests.css";

export const dynamic = "force-dynamic";
const one = <T,>(value: T | T[] | null) => Array.isArray(value) ? value[0] : value;

export default async function ServiceRequestDetail({ params, searchParams }: { params: Promise<{id:string}>; searchParams: Promise<Record<string,string | string[] | undefined>> }) {
  const context = await getWorkspaceContext();
  if (!context) redirect("/account-inactive" as never);
  const { id } = await params;
  const query = await searchParams;
  const { data: item } = await context.supabase.from("service_requests").select("*,customers(full_name,phone),companies(name),service_catalog(name,category)").eq("organization_id",context.organization.id).eq("id",id).maybeSingle();
  if (!item) notFound();
  const [{ data: requirements }, { data: payments }, { data: followUps }, { data: activity }, { data: documents }, { data: members }] = await Promise.all([
    context.supabase.from("service_request_requirements").select("*,documents(id,display_name,expires_on)").eq("organization_id",context.organization.id).eq("service_request_id",id).order("sort_order"),
    context.supabase.from("service_payments").select("*").eq("organization_id",context.organization.id).eq("service_request_id",id).order("paid_at",{ascending:false}),
    context.supabase.from("follow_ups").select("id,due_at,status,note").eq("organization_id",context.organization.id).eq("service_request_id",id).order("due_at",{ascending:false}),
    context.supabase.from("activity_logs").select("id,message,created_at").eq("organization_id",context.organization.id).eq("entity_type","service_request").eq("entity_id",id).order("created_at",{ascending:false}).limit(30),
    context.supabase.from("documents").select("id,display_name,document_type_id,expires_on").eq("organization_id",context.organization.id).eq("customer_id",item.customer_id).is("archived_at",null).order("created_at",{ascending:false}).limit(100),
    context.supabase.from("organization_memberships").select("user_id,role").eq("organization_id",context.organization.id).eq("status","active"),
  ]);
  const customer = one(item.customers); const service = one(item.service_catalog); const company = one(item.companies);
  const status = item.status as RequestStatus;
  const balance = Number(item.total_amount) - Number(item.paid_amount);
  const assignedName = item.assigned_to ? item.assigned_to === context.user.id ? context.profile.full_name || "Me" : item.assigned_to.slice(0,8) : "Unassigned";
  const outstanding = (requirements ?? []).filter(requirement => requirement.required && requirement.status === "missing").length;
  const nextStatuses = allowedTransitions[status].filter(next => !outstanding || !["ready_to_submit","submitted"].includes(next));
  return <WorkspaceShell organizationName={context.organization.name} activePath="/service-requests">
    <header className="page-heading split"><div><Link href="/service-requests">← Service Requests</Link><p className="eyebrow">{item.request_number} · {service?.category}</p><h1>{service?.name ?? "Service request"}</h1><p><Link href={`/customers/${item.customer_id}`}>{customer?.full_name}</Link>{company && <> · <Link href={`/companies/${item.company_id}`}>{company.name}</Link></>} · Assigned to {assignedName}</p></div><div className="service-actions"><span className={`service-status status-${status}`}>{statusLabels[status]}</span><Link className="primary-button" href={`/scan?requirementId=${requirements?.[0]?.id ?? ""}`}>Quick Scan</Link></div></header>
    {typeof query.error === "string" && <p className="form-error">{query.error}</p>}
    {query.created === "1" && <p className="service-notice">Request created. The checklist is ready.</p>}
    <section className="service-summary"><div><small>Total</small><b>{money(item.total_amount)}</b></div><div><small>Paid</small><b>{money(item.paid_amount)}</b></div><div><small>Balance</small><b>{money(balance)}</b></div><div><small>Expected completion</small><b>{item.expected_completion_at ? new Date(item.expected_completion_at).toLocaleDateString("en-AE") : "Not set"}</b></div></section>
    <section className="panel service-card"><div className="service-card-top"><div><h2>Status pipeline</h2><p>{outstanding ? `${outstanding} required document${outstanding === 1 ? " is" : "s are"} missing.` : "Required documents are ready."}</p></div></div><div className="service-pipeline">{requestStatuses.filter(value => !["cancelled","rejected"].includes(value)).map(value => <span className={value === status ? "current" : ""} key={value}>{statusLabels[value]}</span>)}</div>
      <form action={updateServiceRequestStatusAction} className="service-inline-form"><input type="hidden" name="requestId" value={id}/><label>Move to<select name="status" required><option value="">Choose next status</option>{nextStatuses.map(next => <option key={next} value={next}>{statusLabels[next]}</option>)}</select></label><button className="primary-button" disabled={!nextStatuses.length}>Update status</button></form>
      {allowedTransitions[status].includes("completed") && <form action={updateServiceRequestStatusAction}><input type="hidden" name="requestId" value={id}/><input type="hidden" name="status" value="completed"/><button className="secondary-button">Mark completed</button></form>}
    </section>
    <div className="service-detail-grid">
      <section className="panel service-card" id="checklist"><div className="service-card-top"><div><h2>Required documents</h2><p>Attach existing documents or open Quick Scan to capture a new one.</p></div></div>
        {(requirements ?? []).length ? <div className="service-requirements">{requirements!.map(requirement => <article key={requirement.id}><div><b>{requirement.name}</b><small>{requirement.required ? "Required" : "Optional"} · {requirement.status.replace("_"," ")}</small>{one(requirement.documents) && <Link href={`/documents/${requirement.document_id}`}>{one(requirement.documents)?.display_name}</Link>}</div><div className="service-actions"><Link className="secondary-button" href={`/scan?requirementId=${requirement.id}`}>Upload / Quick Scan</Link><form action={updateRequirementAction} className="service-attach"><input type="hidden" name="requestId" value={id}/><input type="hidden" name="requirementId" value={requirement.id}/><select name="documentId" defaultValue={requirement.document_id ?? ""} aria-label={`Document for ${requirement.name}`}><option value="">No document</option>{(documents ?? []).filter(doc => !requirement.document_type_id || doc.document_type_id === requirement.document_type_id).map(doc => <option value={doc.id} key={doc.id}>{doc.display_name}</option>)}</select><select name="status" defaultValue={requirement.status} aria-label={`Status for ${requirement.name}`}><option value="missing">Missing</option><option value="received">Received</option><option value="verified">Verified</option><option value="not_required">Not required</option></select><button className="secondary-button">Save</button></form></div></article>)}</div> : <p className="empty-state">This service has no checklist items. <Link href="/services">Configure the service catalog</Link>.</p>}
      </section>
      <section className="panel service-card"><h2>Application and notes</h2><form action={updateServiceRequestDetailsAction} className="service-form"><input type="hidden" name="requestId" value={id}/><label>Application reference<input name="applicationReference" defaultValue={item.application_reference ?? ""} maxLength={160}/></label><label>External reference<input name="externalReference" defaultValue={item.external_reference ?? ""} maxLength={160}/></label><label>Assigned to<select name="assignedTo" defaultValue={item.assigned_to ?? ""}><option value="">Unassigned</option>{(members ?? []).map(member => <option value={member.user_id} key={member.user_id}>{member.user_id === context.user.id ? context.profile.full_name || "Me" : `${member.role} · ${member.user_id.slice(0,8)}`}</option>)}</select></label><label>Other cost<input name="otherCost" type="number" min="0" step="0.01" defaultValue={item.other_cost}/></label><label>Discount<input name="discount" type="number" min="0" step="0.01" defaultValue={item.discount}/></label><label className="service-wide">Notes<textarea name="notes" rows={4} defaultValue={item.notes ?? ""} maxLength={3000}/></label><button className="primary-button service-wide">Save details</button></form></section>
      <section className="panel service-card" id="payments"><h2>Fees and payment</h2><dl className="service-fees"><div><dt>Government fee</dt><dd>{money(item.government_fee)}</dd></div><div><dt>Other cost</dt><dd>{money(item.other_cost)}</dd></div><div><dt>Service charge</dt><dd>{money(item.service_fee)}</dd></div><div><dt>Discount</dt><dd>− {money(item.discount)}</dd></div><div><dt>Total</dt><dd>{money(item.total_amount)}</dd></div><div><dt>Paid</dt><dd>{money(item.paid_amount)}</dd></div><div><dt>Balance</dt><dd>{money(balance)}</dd></div></dl><p className="service-status">{item.payment_status.replace("_"," ")}</p>
        {balance > 0 && !["cancelled","rejected"].includes(status) && <form action={recordServicePaymentAction} className="service-form"><input type="hidden" name="requestId" value={id}/><label>Amount<input name="amount" type="number" min="0.01" max={balance} step="0.01" required/></label><label>Method<select name="method"><option value="cash">Cash</option><option value="card">Card</option><option value="bank_transfer">Bank transfer</option><option value="other">Other</option></select></label><label>Reference<input name="reference" maxLength={160}/></label><label>Notes<input name="notes" maxLength={500}/></label><button className="primary-button service-wide">Record payment</button></form>}
        {(payments ?? []).length > 0 && <ul className="service-checklist">{payments!.map(payment => <li key={payment.id}><span>{new Date(payment.paid_at).toLocaleDateString("en-AE")} · {payment.method.replace("_"," ")}</span><b>{money(payment.amount)}</b></li>)}</ul>}
      </section>
      <section className="panel service-card" id="follow-ups"><h2>Follow-ups</h2><form action={createServiceFollowUpAction} className="service-form"><input type="hidden" name="requestId" value={id}/><label>Due at<input name="dueAt" type="datetime-local" required/></label><label>Note<input name="note" maxLength={1000} placeholder="Call customer with update"/></label><button className="secondary-button service-wide">Add follow-up</button></form><ul className="service-checklist">{(followUps ?? []).map(value => <li key={value.id}><span>{value.note || "Follow-up"}<small>{new Date(value.due_at).toLocaleString("en-AE")}</small></span><b>{value.status}</b></li>)}</ul></section>
      <section className="panel service-card service-wide" id="activity"><h2>Activity timeline</h2><div className="service-timeline">{(activity ?? []).length ? activity!.map(value => <div key={value.id}><span aria-hidden>●</span><p>{value.message}</p><time>{new Date(value.created_at).toLocaleString("en-AE")}</time></div>) : <p className="empty-state">No activity yet.</p>}</div></section>
    </div>
  </WorkspaceShell>;
}
