"use client";
import Link from "next/link";
import { useMemo, useRef, useState } from "react";
import styles from "./import-uploader.module.css";
type Sheet={name:string;headers:string[];rowCount:number;preview:Record<string,string>[]}; type Row={id:string;row_number:number;source_data:Record<string,string>;normalized_data:Record<string,string|null>;status:string;issues:string[];resolution:string|null}; type Summary={total:number;ready:number;invalid:number;duplicates:number;rows:Row[]};
const fields=["customer_name","customer_phone","customer_email","company_name","company_phone","branch","document_type","document_number","issue_date","expiry_date","notes"]; const labels:Record<string,string>={customer_name:"Customer name",customer_phone:"Phone",customer_email:"Email",company_name:"Company",company_phone:"Company phone",branch:"Branch",document_type:"Document type",document_number:"Document number",issue_date:"Issue date",expiry_date:"Expiry date",notes:"Notes"};
const suggest=(h:string)=>{const x=h.toLowerCase();if(/expiry|expiration/.test(x))return"expiry_date";if(/passport|visa|emirates|eid/.test(x))return"document_number";if(/phone|mobile|contact/.test(x))return"customer_phone";if(/email/.test(x))return"customer_email";if(/company|establishment/.test(x))return"company_name";if(/customer|client|full name|^name$/.test(x))return"customer_name";if(/notes|remarks|comment/.test(x))return"notes";if(/issue/.test(x))return"issue_date";return""};
const sizeLabel=(n:number)=>n<1048576?`${Math.max(1,Math.round(n/1024))} KB`:`${(n/1048576).toFixed(1)} MB`;
export function ImportUploader(){
 const inputRef=useRef<HTMLInputElement>(null); const[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[jobId,setJobId]=useState(""),[sheets,setSheets]=useState<Sheet[]>([]),[selected,setSelected]=useState(""),[mapping,setMapping]=useState<Record<string,string>>({}),[summary,setSummary]=useState<Summary|null>(null),[resolved,setResolved]=useState(false),[progress,setProgress]=useState(""),[editing,setEditing]=useState<Row|null>(null),[draft,setDraft]=useState<Record<string,string|null>>({});
 const sheet=useMemo(()=>sheets.find(s=>s.name===selected)??sheets[0],[sheets,selected]); const mapped=(h:string)=>mapping[h]??suggest(h); const step=progress?4:summary?3:jobId?2:1;
 async function upload(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!file)return;setBusy(true);setError("");const r=await fetch("/api/imports/parse",{method:"POST",body:new FormData(e.currentTarget)}),b=await r.json();setBusy(false);if(!r.ok)return setError(b.error??"Upload failed. Check the file and try again.");setJobId(b.jobId);setSheets(b.sheets);setSelected(b.sheets[0]?.name??"");setSummary(null)}
 async function validate(){if(!sheet)return;setBusy(true);const r=await fetch(`/api/imports/${jobId}/validate`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sheetName:sheet.name,mapping:Object.fromEntries(sheet.headers.map(h=>[h,mapped(h)]))})}),b=await r.json();setBusy(false);if(!r.ok)return setError(b.error??"Validation failed. Review the field mapping.");setSummary(b);setResolved(b.duplicates===0)}
 async function resolve(resolution:"skip"|"update"|"create"){const rowIds=summary?.rows.filter(r=>r.status==="possible_duplicate").map(r=>r.id)??[];setBusy(true);const r=await fetch(`/api/imports/${jobId}/resolve`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({rowIds,resolution})}),b=await r.json();setBusy(false);if(!r.ok)return setError(b.error??"Could not save the duplicate decision.");setResolved(true)}
 async function saveRow(){if(!editing)return;setBusy(true);const r=await fetch(`/api/imports/${jobId}/rows/${editing.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(draft)}),b=await r.json();setBusy(false);if(!r.ok)return setError(b.error??"Could not save the staged row.");setSummary(s=>s?{...s,rows:s.rows.map(row=>row.id===editing.id?{...row,normalized_data:b.normalized,status:b.status,issues:b.issues}:row)}:s);setEditing(null)}
 async function execute(){setBusy(true);let done=false;while(!done){const r=await fetch(`/api/imports/${jobId}/execute`,{method:"POST"}),b=await r.json();if(!r.ok){setError(b.error??"Import failed. Try again or download the error report.");break}done=b.complete;setProgress(done?"Import complete. Records are now available in your workspace.":`${b.remaining} records remaining…`)}setBusy(false)}
 function edit(row:Row){setEditing(row);setDraft(row.normalized_data)} function clearFile(){setFile(null);if(inputRef.current)inputRef.current.value=""}
 return <section className={styles.workflow}><header className="page-heading"><p className="eyebrow">Data management</p><h1>Import Data</h1><p>Upload CSV or Excel files. Nothing is written until you confirm.</p></header>
 <ol className={styles.steps} aria-label="Import progress">{["Upload","Match","Review","Import"].map((label,index)=><li className={step===index+1?styles.current:step>index+1?styles.complete:""} key={label}><span>{index+1}</span>{label}</li>)}</ol>
 <section className={`panel ${styles.panel}`}><h2>Upload your data</h2><form onSubmit={upload} className={styles.uploadForm}><input ref={inputRef} className={styles.fileInput} name="file" type="file" accept=".csv,.xlsx,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" required onChange={e=>setFile(e.target.files?.[0]??null)}/><div className={styles.uploadCard}><svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7"><path d="M12 16V4m0 0L8 8m4-4 4 4M5 14v5h14v-5"/></svg><div><b>Upload CSV or Excel</b><span>CSV or XLSX · Up to 15 MB · 5,000 rows</span></div><button type="button" className="secondary-button" onClick={()=>inputRef.current?.click()}>{file?"Change file":"Choose file"}</button></div>{file&&<div className={styles.selectedFile}><span><b>{file.name}</b><small>{sizeLabel(file.size)}</small></span><button type="button" onClick={clearFile}>Remove</button></div>}<button className={`primary-button ${styles.analyse}`} disabled={busy||!file}>{busy?"Analysing…":"Analyse file"}</button></form></section>
 {error&&<p className={styles.error} role="alert">{error}</p>}
 {jobId&&sheet&&<section className={`panel ${styles.panel}`}><h2>Match fields</h2><div className={styles.mapping}>{sheet.headers.map(h=><label key={h}><span>{h}</span><select value={mapped(h)} onChange={e=>setMapping({...mapping,[h]:e.target.value})}><option value="">Do not import</option>{fields.map(f=><option key={f} value={f}>{labels[f]}</option>)}</select></label>)}</div><button className="primary-button" type="button" onClick={validate} disabled={busy}>Validate and preview</button></section>}
 {summary&&<section className={`panel ${styles.panel}`}><h2>Review records</h2><p>{summary.ready} ready · {summary.duplicates} possible duplicates · {summary.invalid} need review.</p>{summary.duplicates>0&&<div className={styles.duplicates}><button onClick={()=>resolve("skip")} disabled={busy}>Skip duplicates</button><button onClick={()=>resolve("update")} disabled={busy}>Update existing</button><button onClick={()=>resolve("create")} disabled={busy}>Create new anyway</button></div>}<div className={styles.reviewTable}><table><thead><tr><th>Row</th><th>Status</th><th>Record</th><th>Issue</th><th>Action</th></tr></thead><tbody>{summary.rows.map(row=><tr key={row.id}><td>{row.row_number}</td><td>{row.status.replaceAll("_"," ")}</td><td>{row.normalized_data.customer_name??row.normalized_data.company_name??"—"}</td><td>{row.issues?.join(" ")||"—"}</td><td><button type="button" onClick={()=>edit(row)}>Edit</button></td></tr>)}</tbody></table></div><div className={styles.reviewCards}>{summary.rows.map(row=><article key={row.id}><header><b>{row.normalized_data.customer_name??row.normalized_data.company_name??`Row ${row.row_number}`}</b><span>{row.status.replaceAll("_"," ")}</span></header><small>Row {row.row_number}</small>{row.issues?.length>0&&<p>{row.issues.join(" ")}</p>}<button type="button" onClick={()=>edit(row)}>Edit row</button></article>)}</div>{summary.invalid>0&&<a href={`/api/imports/${jobId}/error-report`}>Download Error Report</a>}<div className={styles.confirmBar}><button className="primary-button" type="button" onClick={execute} disabled={busy||!summary.ready||!resolved}>{busy?"Importing…":"Confirm & Import"}</button></div></section>}
 {editing&&<section className={`panel ${styles.panel} ${styles.edit}`}><h2>Edit staged row {editing.row_number}</h2><p>Changes affect only this import preview.</p><div className={styles.mapping}>{["customer_name","company_name","customer_phone","customer_email","document_type","document_number","issue_date","expiry_date","notes"].map(f=><label key={f}><span>{labels[f]}</span><input value={draft[f]??""} onChange={e=>setDraft({...draft,[f]:e.target.value})}/></label>)}</div><div className={styles.editActions}><button className="primary-button" onClick={saveRow} disabled={busy}>{busy?"Saving…":"Save and revalidate"}</button><button className="secondary-button" onClick={()=>setEditing(null)} disabled={busy}>Cancel</button></div></section>}
 {progress&&<section className={`panel ${styles.panel}`} role="status"><h2>Import Complete</h2><p>{progress}</p><Link className="primary-button" href="/customers">View Customers</Link></section>}</section>}
