import { z } from "zod";

export const CANONICAL_DOCUMENT_CODES = ["emirates_id","passport","residence_visa","visit_visa","employment_visa","family_visa","golden_visa","labour_card","work_permit","medical_insurance","health_card","medical_fitness_certificate","driving_licence","vehicle_registration","vehicle_insurance","trade_licence","establishment_card","immigration_card","mohre_establishment_card","chamber_certificate","vat_tax_registration","memorandum_of_association","tenancy_contract","noc","power_of_attorney","other"] as const;
export const canonicalDocumentCodeSchema = z.enum(CANONICAL_DOCUMENT_CODES);
export type CanonicalDocumentCode = z.infer<typeof canonicalDocumentCodeSchema>;
export const canonicalDocumentClassificationSchema = z.object({ canonicalCode: canonicalDocumentCodeSchema.nullable() }).strict();
export const CANONICAL_DOCUMENT_LABELS: Record<CanonicalDocumentCode, string> = { emirates_id:"Emirates ID", passport:"Passport", residence_visa:"Residence Visa", visit_visa:"Visit Visa", employment_visa:"Employment Visa", family_visa:"Family Visa", golden_visa:"Golden Visa", labour_card:"Labour Card", work_permit:"Work Permit", medical_insurance:"Medical Insurance", health_card:"Health Card", medical_fitness_certificate:"Medical Fitness Certificate", driving_licence:"Driving Licence", vehicle_registration:"Vehicle Registration / Mulkiya", vehicle_insurance:"Vehicle Insurance", trade_licence:"Trade Licence", establishment_card:"Establishment Card", immigration_card:"Immigration Card", mohre_establishment_card:"MOHRE Establishment Card", chamber_certificate:"Chamber of Commerce Certificate", vat_tax_registration:"VAT / Tax Registration", memorandum_of_association:"Memorandum of Association", tenancy_contract:"Tenancy Contract / Ejari", noc:"NOC", power_of_attorney:"Power of Attorney", other:"Other" };

// Only exact legacy semantic equivalents are safe to translate; broad categories stay unresolved.
export const legacyExtractionCanonicalCode = (value: string): CanonicalDocumentCode | null => ({ passport:"passport", emirates_id:"emirates_id", trade_license:"trade_licence", establishment_card:"establishment_card", labour_card:"labour_card", work_permit:"work_permit", vehicle_registration:"vehicle_registration", other:"other" } as Partial<Record<string, CanonicalDocumentCode>>)[value] ?? null;
