import { redirect } from "next/navigation";
import { WorkspaceShell } from "@/components/workspace-shell";
import { getWorkspaceContext } from "@/lib/workspace/context";

export const dynamic = "force-dynamic";
export default async function Dashboard() {
  const context = await getWorkspaceContext();
  if (!context) redirect("/account-inactive" as never);
  const today = new Date(); const todayStart = new Date(today.getFullYear(), today.getMonth(), today.getDate()).toISOString(); const tomorrow = new Date(today.getFullYear(), today.getMonth(), today.getDate() + 1).toISOString(); const inSeven = new Date(today.getTime() + 7 * 86400000).toISOString().slice(0, 10); const inThirty = new Date(today.getTime() + 30 * 86400000).toISOString().slice(0, 10);
  const count = (table: string, filter?: (query: any) => any) => { let query = context.supabase.from(table).select("id", { count: "exact", head: true }).eq("organization_id", context.organization.id); if (filter) query = filter(query); return query; };
  const [{ count: expired }, { count: week }, { count: month }, { count: followUps }, { count: companies }, { count: customers }, { data: attention }, { data: activity }] = await Promise.all([
    count("documents", (q) => q.lt("expires_on", today.toISOString().slice(0, 10)).is("archived_at", null)), count("documents", (q) => q.gte("expires_on", today.toISOString().slice(0, 10)).lte("expires_on", inSeven).is("archived_at", null)), count("documents", (q) => q.gte("expires_on", today.toISOString().slice(0, 10)).lte("expires_on", inThirty).is("archived_at", null)), count("follow_ups", (q) => q.gte("due_at", todayStart).lt("due_at", tomorrow).neq("status", "completed")), count("companies", (q) => q.is("archived_at", null)), count("customers", (q) => q.is("archived_at", null)), context.supabase.from("documents").select("id, expires_on, status, customers(full_name), companies(name)").eq("organization_id", context.organization.id).is("archived_at", null).lte("expires_on", inSeven).order("expires_on").limit(5), context.supabase.from("activity_logs").select("id, message, created_at").eq("organization_id", context.organization.id).order("created_at", { ascending: false }).limit(5),
  ]);
  const cards = [["Expired", expired ?? 0], ["Expiring in 7 days", week ?? 0], ["Expiring in 30 days", month ?? 0], ["Follow-ups today", followUps ?? 0]];
  return <WorkspaceShell organizationName={context.organization.name}><header className="page-heading"><div><p className="eyebrow">Workspace overview</p><h1>Document overview</h1><p>Live, tenant-scoped records for {context.organization.location}.</p></div></header><section className="metric-grid">{cards.map(([label, value]) => <article className="metric-card" key={String(label)}><span>{label}</span><strong>{value}</strong></article>)}</section><section className="dashboard-grid"><article className="panel"><div className="panel-heading"><div><h2>Needs attention</h2><p>Documents due within seven days.</p></div></div>{attention?.length ? <div className="stack">{attention.map((document: any) => <div className="row" key={document.id}><div><b>{document.customers?.full_name ?? document.companies?.name ?? "Document"}</b><small>{document.status}</small></div><time>{document.expires_on}</time></div>)}</div> : <div className="empty-state">No urgent document expiries.</div>}</article><article className="panel"><div className="panel-heading"><div><h2>Today’s follow-ups</h2><p>{followUps ?? 0} scheduled today.</p></div></div><div className="empty-state">Follow-up scheduling is available from a customer profile.</div></article><article className="panel"><div className="panel-heading"><div><h2>Document health</h2><p>Current portfolio overview.</p></div></div><div className="health-list"><span><b>{companies ?? 0}</b> active companies</span><span><b>{customers ?? 0}</b> active customers</span><span><b>{month ?? 0}</b> due within 30 days</span></div></article><article className="panel"><div className="panel-heading"><div><h2>Recent activity</h2><p>Safe operational events only.</p></div></div>{activity?.length ? <div className="stack">{activity.map((item: any) => <div className="row" key={item.id}><b>{item.message}</b><time>{new Date(item.created_at).toLocaleDateString()}</time></div>)}</div> : <div className="empty-state">No recent activity yet.</div>}</article></section></WorkspaceShell>;
}
