import Link from "next/link";
import { redirect } from "next/navigation";
import { WorkspaceShell } from "@/components/workspace-shell";
import { completeFollowUpAction } from "@/features/crm/actions";
import { getRelativeExpiryText } from "@/lib/dates/expiry";
import { getWorkspaceContext } from "@/lib/workspace/context";

export const dynamic = "force-dynamic";

const initials = (name: string) => name.split(/\s+/).map((part) => part[0]).slice(0, 2).join("").toUpperCase();
const relation = <T,>(item: T | T[] | null | undefined) => Array.isArray(item) ? item[0] : item;

function statusFor(date: string) { const relative = getRelativeExpiryText(date); if (relative.startsWith("Expired")) return ["Expired", "danger"] as const; const days = Math.ceil((new Date(`${date}T00:00:00Z`).getTime() - Date.now()) / 86400000); return [days <= 7 ? "Expiring soon" : "In 30 days", days <= 7 ? "warning" : "amber"] as const; }

export default async function Dashboard() {
  const context = await getWorkspaceContext();
  if (!context) redirect("/account-inactive" as never);
  const today = new Date(); const date = today.toISOString().slice(0, 10); const todayStart = new Date(today.getFullYear(), today.getMonth(), today.getDate()).toISOString(); const tomorrow = new Date(today.getFullYear(), today.getMonth(), today.getDate() + 1).toISOString(); const inSeven = new Date(today.getTime() + 7 * 86400000).toISOString().slice(0, 10); const inThirty = new Date(today.getTime() + 30 * 86400000).toISOString().slice(0, 10);
  const count = (table: "documents" | "follow_ups", filter?: (query: any) => any) => { let query = context.supabase.from(table).select("id", { count: "exact", head: true }).eq("organization_id", context.organization.id); if (filter) query = filter(query); return query; };
  const [{ count: expired }, { count: week }, { count: month }, { count: followUps }, { data: attention }, { data: todaysFollowUps }] = await Promise.all([
    count("documents", q => q.lt("expires_on", date).is("archived_at", null)), count("documents", q => q.gte("expires_on", date).lte("expires_on", inSeven).is("archived_at", null)), count("documents", q => q.gte("expires_on", date).lte("expires_on", inThirty).is("archived_at", null)), count("follow_ups", q => q.gte("due_at", todayStart).lt("due_at", tomorrow).neq("status", "completed")),
    context.supabase.from("documents").select("id, display_name, expires_on, status, customer_id, company_id, customers(full_name), companies(name)").eq("organization_id", context.organization.id).is("archived_at", null).lte("expires_on", inSeven).order("expires_on").limit(5),
    context.supabase.from("follow_ups").select("id, due_at, status, note, customer_id, company_id, customers(full_name), companies(name)").eq("organization_id", context.organization.id).gte("due_at", todayStart).lt("due_at", tomorrow).neq("status", "completed").order("due_at").limit(5),
  ]);
  const cards = [["Expired", expired ?? 0, "!", "danger", "Requires action", "/customers"], ["Expiring in 7 days", week ?? 0, "◷", "warning", "Contact customers soon", "/customers"], ["Expiring in 30 days", month ?? 0, "▣", "info", "Upcoming renewals", "/customers"], ["Follow-ups today", followUps ?? 0, "☷", "purple", "Scheduled today", "/follow-ups"]] as const;
  return <WorkspaceShell organizationName={context.organization.name}>
    <header className="page-heading dashboard-hero"><div><h1>Document Overview</h1><p>Monitor upcoming expiries and renewal actions.</p></div></header>
    <section className="metric-grid" aria-label="Document overview metrics">{cards.map(([label, value, icon, color, description, href]) => <Link href={href} className={`metric-card metric-${color}`} key={label}><span className="metric-icon" aria-hidden>{icon}</span><span className="metric-copy"><small>{label}</small><strong>{value}</strong><em>{description}</em></span><span className="metric-arrow" aria-hidden>›</span></Link>)}</section>
    <section className="dashboard-primary">
      <article className="panel attention-panel"><div className="panel-heading"><div className="section-title"><span className="section-icon" aria-hidden>▤</span><div><h2>Needs Attention</h2><p>Documents that require action soon.</p></div></div><Link className="ghost-action" href="/customers">View all <span aria-hidden>›</span></Link></div>
        {attention?.length ? <><div className="attention-table-wrap"><table className="attention-table"><thead><tr><th>Customer / company</th><th>Document</th><th>Expiry</th><th>Status</th><th>Action</th></tr></thead><tbody>{attention.map((document: any) => { const customer = relation(document.customers); const company = relation(document.companies); const owner = customer?.full_name || company?.name || "Unassigned record"; const [status, tone] = statusFor(document.expires_on); const target = document.customer_id ? `/customers/${document.customer_id}` : document.company_id ? `/companies/${document.company_id}` : "/customers"; return <tr key={document.id}><td><span className="person"><span className="initial-avatar">{initials(owner)}</span><span><b>{owner}</b><small>{company?.name && customer ? company.name : "Document record"}</small></span></span></td><td><b>{document.display_name || "Document"}</b></td><td><time title={document.expires_on}>{getRelativeExpiryText(document.expires_on)}</time></td><td><span className={`status-pill ${tone}`}>{status}</span></td><td><Link className="table-action" href={target}>View details</Link></td></tr>; })}</tbody></table></div><div className="attention-mobile-list">{attention.map((document: any) => { const customer = relation(document.customers); const company = relation(document.companies); const owner = customer?.full_name || company?.name || "Unassigned record"; const [status, tone] = statusFor(document.expires_on); const target = document.customer_id ? `/customers/${document.customer_id}` : document.company_id ? `/companies/${document.company_id}` : "/customers"; return <article className="attention-mobile-card" key={document.id}><span className="person"><span className="initial-avatar">{initials(owner)}</span><span><b>{owner}</b><small>{document.display_name || "Document"}</small></span></span><span className={`status-pill ${tone}`}>{status} · {getRelativeExpiryText(document.expires_on)}</span><Link className="table-action" href={target}>View details</Link></article>; })}</div></> : <div className="dashboard-empty"><span aria-hidden>▤</span><b>Nothing needs attention</b><p>Your upcoming document expiries will appear here.</p></div>}
      </article>
      <article className="panel followups-panel"><div className="panel-heading"><div className="section-title"><span className="section-icon" aria-hidden>▦</span><div><h2>Today&apos;s Follow-Ups</h2><p>Customers to contact today</p></div></div><Link className="add-action" href="/follow-ups">＋ Add</Link></div>
        {todaysFollowUps?.length ? <div className="followup-list">{todaysFollowUps.map((item: any) => { const customer = relation(item.customers); const company = relation(item.companies); const person = customer?.full_name || company?.name || "Follow-up"; const overdue = item.due_at < new Date().toISOString(); return <article className="followup-item" key={item.id}><span className="initial-avatar">{initials(person)}</span><span className="followup-copy"><b>{person}</b><small>{item.note || company?.name || "Follow-up"}</small></span><span className="followup-meta"><time>{new Intl.DateTimeFormat("en-AE", { hour: "numeric", minute: "2-digit" }).format(new Date(item.due_at))}</time><span className={`status-pill ${overdue ? "warning" : "amber"}`}>{overdue ? "Due" : "Pending"}</span></span><form action={completeFollowUpAction}><input type="hidden" name="followUpId" value={item.id}/><input type="hidden" name="customerResponse" value=""/><input type="hidden" name="nextDueAt" value=""/><input type="hidden" name="nextNote" value=""/><button aria-label={`Mark follow-up with ${person} complete`} className="complete-check" type="submit">✓</button></form></article>; })}</div> : <div className="dashboard-empty compact"><span aria-hidden>✓</span><b>No follow-ups for today</b><p>Scheduled customer contacts will appear here.</p></div>}
        <Link className="panel-footer-link" href="/follow-ups">View all follow-ups <span aria-hidden>›</span></Link>
      </article>
    </section>
  </WorkspaceShell>;
}
